package provider

import (
	"context"
	"maps"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/fluencelabs/terraform-provider-rauthy/internal/provider/validators"
)

// optionalComputedNote is appended to every attribute that Rauthy insists on
// having a value for. It is the same trade-off everywhere, so it is worth
// saying in the same words everywhere.
const optionalComputedNote = "\n\nOptional and computed: leaving this out adopts whatever Rauthy has, " +
	"and removing it from the configuration later keeps the last applied value rather than reverting it. " +
	"To change it, set it explicitly."

// clientResourceDescription is the resource's own documentation, including the
// note on optional-and-computed attributes that the whole design hinges on.
const clientResourceDescription = "An OIDC client in Rauthy.\n\n" +
	"Creating one takes two API calls: `POST /clients` accepts only the id, name, confidentiality " +
	"and the redirect URIs and silently ignores everything else, so the provider immediately follows " +
	"it with `PUT /clients/{id}` carrying the full configuration.\n\n" +
	"A confidential client's secret is generated by Rauthy and cannot be supplied from outside, " +
	"which is why `secret` is a read-only attribute rather than something you set.\n\n" +
	"## Attributes that are optional and computed\n\n" +
	"Most settings on this resource are both optional and computed, and that has a consequence " +
	"worth knowing before you rely on it.\n\n" +
	"`PUT /clients/{id}` is a full replacement: Rauthy requires a concrete value for `enabled`, " +
	"`flows_enabled`, `scopes`, `default_scopes`, both signing algorithms, both lifetimes and " +
	"`force_mfa` on every update, and rejects a request that omits any of them. The provider " +
	"therefore always has to send something. When you do not configure an attribute, it sends " +
	"back whatever Rauthy currently has — the defaults Rauthy chose when the client was created.\n\n" +
	"The cost is that **removing such an attribute from your configuration does not revert it**. " +
	"Terraform keeps the last applied value and the provider keeps sending it, so the setting " +
	"stays where you left it. To change one of these settings, set it explicitly; there is no " +
	"way to say \"go back to the default\" other than writing the default down.\n\n" +
	"The alternative — the provider carrying its own hardcoded defaults — was rejected " +
	"deliberately: those defaults would drift away from Rauthy's on the next upgrade and " +
	"silently rewrite clients nobody meant to touch."

func (r *clientResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	attributes := make(map[string]schema.Attribute)
	maps.Copy(attributes, clientIdentityAttributes())
	maps.Copy(attributes, clientBehaviourAttributes())
	maps.Copy(attributes, clientDescriptiveAttributes())
	maps.Copy(attributes, clientSecretAttributes())

	resp.Schema = schema.Schema{
		MarkdownDescription: clientResourceDescription,
		Attributes:          attributes,
	}
}

// clientIdentityAttributes covers who the client is and where it may send
// users: the fields Rauthy already accepts on POST /clients.
func clientIdentityAttributes() map[string]schema.Attribute {
	// Every Optional+Computed attribute below carries UseStateForUnknown.
	//
	// Without it, updating a client fails outright. Established by experiment,
	// not by reading the framework: with the modifiers removed, an update sends
	// `"flows_enabled": null` (captured off the wire) and Rauthy answers
	// "invalid type: null, expected a sequence"; with them, the same update
	// succeeds. Since UseStateForUnknown does nothing unless the planned value
	// is unknown, that value was unknown — an Optional+Computed attribute the
	// configuration never mentions.
	//
	// Keeping prior state is also what these attributes mean: the practitioner
	// expressed no opinion, so whatever Rauthy already holds stands. At Create
	// there is no prior state, the modifiers are no-ops, and the values still
	// come from the creation response.
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Required:            true,
			MarkdownDescription: "The client id, as used in OIDC requests. Changing it replaces the client.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
			Validators: []validator.String{validators.ClientID()},
		},
		"name": schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: "Human-readable name, shown on the login page.",
			Validators:          []validator.String{validators.ClientName()},
		},
		"confidential": schema.BoolAttribute{
			Required: true,
			MarkdownDescription: "Whether the client authenticates with a secret. A public client " +
				"(`false`) has no secret and Rauthy requires S256 PKCE from it.",
		},
		"enabled": schema.BoolAttribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Whether the client may be used to log in." + optionalComputedNote,
			PlanModifiers: []planmodifier.Bool{
				boolplanmodifier.UseStateForUnknown(),
			},
		},
		"redirect_uris": schema.SetAttribute{
			Required:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Allowed redirect URIs.",
			Validators:          []validator.Set{validators.URISet()},
		},
		"post_logout_redirect_uris": schema.SetAttribute{
			Optional:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Allowed redirect URIs after a logout.",
			Validators:          []validator.Set{validators.URISet()},
		},
		"allowed_origins": schema.SetAttribute{
			Optional:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Additional CORS origins, as `scheme://host[:port]` with no path.",
			Validators:          []validator.Set{validators.OriginSet()},
		},
	}
}

// clientBehaviourAttributes covers everything that only PUT /clients/{id}
// accepts: flows, scopes, token settings and the rest of the configuration.
func clientBehaviourAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"flows_enabled": schema.SetAttribute{
			Optional:    true,
			Computed:    true,
			ElementType: types.StringType,
			MarkdownDescription: "Enabled OAuth 2.0 flows: `authorization_code`, `client_credentials`, " +
				"`urn:ietf:params:oauth:grant-type:device_code`, `password`, `refresh_token`." +
				optionalComputedNote,
			Validators: validators.FlowsEnabledSet(),
			PlanModifiers: []planmodifier.Set{
				setplanmodifier.UseStateForUnknown(),
			},
		},
		"access_token_alg": schema.StringAttribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Signing algorithm for access tokens: `RS256`, `RS384`, `RS512` or `EdDSA`." + optionalComputedNote,
			Validators:          []validator.String{validators.SigningAlg()},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"id_token_alg": schema.StringAttribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Signing algorithm for id tokens: `RS256`, `RS384`, `RS512` or `EdDSA`." + optionalComputedNote,
			Validators:          []validator.String{validators.SigningAlg()},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"auth_code_lifetime": schema.Int64Attribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Lifetime of an authorization code in seconds (10-300)." + optionalComputedNote,
			Validators:          []validator.Int64{validators.AuthCodeLifetime()},
			PlanModifiers: []planmodifier.Int64{
				int64planmodifier.UseStateForUnknown(),
			},
		},
		"access_token_lifetime": schema.Int64Attribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Lifetime of an access token in seconds (10-86400)." + optionalComputedNote,
			Validators:          []validator.Int64{validators.AccessTokenLifetime()},
			PlanModifiers: []planmodifier.Int64{
				int64planmodifier.UseStateForUnknown(),
			},
		},
		"scopes": schema.SetAttribute{
			Optional:            true,
			Computed:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Scopes the client may request." + optionalComputedNote,
			Validators:          []validator.Set{validators.ScopeSet()},
			PlanModifiers: []planmodifier.Set{
				setplanmodifier.UseStateForUnknown(),
			},
		},
		"default_scopes": schema.SetAttribute{
			Optional:            true,
			Computed:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Scopes granted even when the client does not ask for them." + optionalComputedNote,
			Validators:          []validator.Set{validators.ScopeSet()},
			PlanModifiers: []planmodifier.Set{
				setplanmodifier.UseStateForUnknown(),
			},
		},
		"challenges": schema.SetAttribute{
			Optional:    true,
			Computed:    true,
			ElementType: types.StringType,
			MarkdownDescription: "Accepted PKCE challenge methods: `plain`, `S256`. Rauthy requires " +
				"`S256` from public clients regardless of this setting." + optionalComputedNote,
			Validators: validators.ChallengeSet(),
			PlanModifiers: []planmodifier.Set{
				setplanmodifier.UseStateForUnknown(),
			},
		},
		"force_mfa": schema.BoolAttribute{
			Optional:            true,
			Computed:            true,
			MarkdownDescription: "Require MFA for users logging in through this client." + optionalComputedNote,
			PlanModifiers: []planmodifier.Bool{
				boolplanmodifier.UseStateForUnknown(),
			},
		},
	}
}

// clientDescriptiveAttributes covers the informational and access-restriction
// fields: they change nothing about the OIDC exchange itself.
func clientDescriptiveAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"client_uri": schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: "Informational URI of the application.",
			Validators:          []validator.String{validators.URI()},
		},
		"contacts": schema.SetAttribute{
			Optional:            true,
			ElementType:         types.StringType,
			MarkdownDescription: "Contact addresses for the application's maintainers.",
			Validators:          []validator.Set{validators.ContactSet()},
		},
		"backchannel_logout_uri": schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: "OIDC back-channel logout endpoint of the application.",
			Validators:          []validator.String{validators.URI()},
		},
		"restrict_group_prefix": schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: "Restrict logins to users in groups starting with this prefix.",
			Validators:          []validator.String{validators.GroupPrefix()},
		},
		"scim": schema.SingleNestedAttribute{
			Optional:            true,
			MarkdownDescription: "SCIM provisioning against the application.",
			Attributes: map[string]schema.Attribute{
				"bearer_token": schema.StringAttribute{
					Required:            true,
					Sensitive:           true,
					MarkdownDescription: "Bearer token Rauthy presents to the SCIM endpoint.",
				},
				"base_uri": schema.StringAttribute{
					Required:            true,
					MarkdownDescription: "Base URI of the SCIM endpoint.",
					Validators:          []validator.String{validators.URI()},
				},
				"sync_groups": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: "Whether groups are synchronised as well as users.",
				},
				"group_sync_prefix": schema.StringAttribute{
					Optional:            true,
					MarkdownDescription: "Only synchronise groups starting with this prefix.",
					Validators:          []validator.String{validators.GroupPrefix()},
				},
			},
		},
	}
}

// clientSecretAttributes covers the secret and the two attributes that steer
// its rotation.
func clientSecretAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"secret": schema.StringAttribute{
			Computed:  true,
			Sensitive: true,
			MarkdownDescription: "The client secret, generated by Rauthy. Null for a public client.\n\n" +
				"Rauthy does not accept a secret from outside, so this cannot be set; read it from here " +
				"and put it wherever it needs to go.",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"secret_rotation_trigger": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: "Rotates the client secret whenever this value changes. The value itself " +
				"means nothing — a timestamp or a version string is the usual choice. Rotation never " +
				"happens on its own.\n\n" +
				"Not populated on import, since Rauthy has no notion of it.",
		},
		"secret_cache_current_hours": schema.Int64Attribute{
			Optional: true,
			MarkdownDescription: "How long (1-24 hours) the previous secret keeps working after a " +
				"rotation, giving consumers time to pick up the new one. Sent only when a rotation " +
				"actually happens; changing this on its own does not rotate anything.\n\n" +
				"Not populated on import.",
			Validators: []validator.Int64{validators.CacheCurrentHours()},
		},
	}
}
